### ISSUE TITLE
Please add multiline code blocks to the REPL.

### ISSUE THREAD

**Issue by t0md3an** [haifenghuang/magpie#5]
@haifenghuang 

Please add multiline code blocks to the REPL. It would be very convenient.

```
>>> fn sum(x, y) {
...     return x + y
... }
>>>
```

**instead of:**

```
>>> fn sum(x, y) { return x + y }
```

The magpie is amazing! Thanks!

**Comment by haifenghuang** [comment]
The REPL already support multi-line support for code blocks if you end a line with a '\'. But as you might think, it's very inconvenience. so I've improved the REPL according to your suggestion.

**Comment by t0md3an** [comment]
@haifenghuang Thank you.

Is it possible to do something like this

```
magpie>> println(
... "hi"
... )
hi
magpie>>
```

instead of

```
magpie>> println(
... "hi"
... )
... 
hi
magpie>>
```

?

**Comment by haifenghuang** [comment]
It's possible.
After you typed ')', you should enter a new line without any code, that will terminate the expression/statement.

```
magpie>> println(
... "hi"
... )
...   # Here you must enter a new line.
hi
magpie>>
```

**Comment by t0md3an** [comment]
@haifenghuang I think repl can check every line and the line that will not return an error can be a terminator for expression/statement.

**Comment by haifenghuang** [comment]
Yes, you are right. At first, I think it would be very complicated. After think a while, I found a better & simpler way to do it.
